"""..

Revision ID: 0afafa592896
Revises: 8ba4c4caa86b
Create Date: 2018-01-04 11:15:14.213862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0afafa592896'
down_revision = '8ba4c4caa86b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('filish', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'filish')
    # ### end Alembic commands ###
