"""..

Revision ID: 1dba5b8a3ddd
Revises: 5af8cc077276
Create Date: 2018-01-03 14:16:09.868524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1dba5b8a3ddd'
down_revision = '5af8cc077276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_timenode', table_name='tasks')
    op.drop_column('tasks', 'timenode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('timenode', mysql.DATETIME(), nullable=True))
    op.create_index('ix_tasks_timenode', 'tasks', ['timenode'], unique=False)
    # ### end Alembic commands ###
