"""..

Revision ID: 44272897b27c
Revises: f84b465f4eb0
Create Date: 2018-01-06 14:18:24.000019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44272897b27c'
down_revision = 'f84b465f4eb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_titles_title'), 'titles', ['title'], unique=False)
    op.add_column('tasks', sa.Column('title', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'titles', ['title'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'title')
    op.drop_index(op.f('ix_titles_title'), table_name='titles')
    op.drop_table('titles')
    # ### end Alembic commands ###
