"""..

Revision ID: 45ac2d6af57a
Revises: 44272897b27c
Create Date: 2018-01-06 14:23:26.724494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ac2d6af57a'
down_revision = '44272897b27c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('titles', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'titles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'titles', type_='foreignkey')
    op.drop_column('titles', 'user_id')
    # ### end Alembic commands ###
