"""..

Revision ID: 59052f4ce9e5
Revises: 7fb636f1087b
Create Date: 2018-01-02 19:00:08.388185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59052f4ce9e5'
down_revision = '7fb636f1087b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('icon', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'icon')
    # ### end Alembic commands ###
