"""..

Revision ID: 6f8f41499810
Revises: 1dba5b8a3ddd
Create Date: 2018-01-03 14:16:30.455374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f8f41499810'
down_revision = '1dba5b8a3ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('timenode', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_tasks_timenode'), 'tasks', ['timenode'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_timenode'), table_name='tasks')
    op.drop_column('tasks', 'timenode')
    # ### end Alembic commands ###
